export const routes = {
  home: "/",
  jobs: "/jobs",
  pricing: "/pricing",
  successStories: "/success-stories",
  feedback: "/feedback",
  employers: "/for-employers",
  about: "/about",
  contact: "/contact",
  legal: {
    terms: "/legal/terms",
    privacy: "/legal/privacy",
    refund: "/legal/refund",
    disclaimer: "/legal/disclaimer",
    candidateAgreement: "/legal/candidate-agreement",
    employerTerms: "/legal/employer-terms",
  },
  auth: {
    login: "/login",
    register: "/register",
    candidateLogin: "/candidate-login",
    employerLogin: "/employer-login",
    adminLogin: "/nextedge-secure-admin-access",
    candidateRegister: "/candidate-register",
    employerRegister: "/employer-register",
    registerCandidate: "/register/candidate",
    registerEmployer: "/register/employer",
    forgotPassword: "/forgot-password",
    verifyOtp: "/verify-otp",
    resetPassword: "/reset-password",
  },
  candidate: {
    dashboard: "/candidate/dashboard",
    jobs: "/candidate/jobs",
    preferences: "/candidate/preferences",
    savedJobs: "/candidate/saved-jobs",
    applications: "/candidate/applications",
    agreements: "/candidate/agreements",
    membership: "/candidate/membership",
    payments: "/candidate/payments",
    feedback: "/candidate/feedback",
    support: "/candidate/support",
  },
  employer: {
    dashboard: "/employer/dashboard",
    jobs: "/employer/jobs",
    jobsNew: "/employer/jobs/new",
    candidates: "/employer/candidates",
    interviews: "/employer/interviews",
    companyProfile: "/employer/company-profile",
    support: "/employer/support",
  },
  admin: {
    dashboard: "/admin/dashboard",
    jobs: "/admin/jobs",
    jobsPending: "/admin/jobs/pending",
    applications: "/admin/applications",
    candidates: "/admin/candidates",
    employers: "/admin/employers",
    payments: "/admin/payments",
    agreements: "/admin/agreements",
    legal: "/admin/legal",
    feedback: "/admin/feedback",
    support: "/admin/support",
    resumeCleanup: "/admin/resume-cleanup",
    notifications: "/admin/notifications",
    masterData: "/admin/master-data",
    settings: "/admin/settings",
    auditLogs: "/admin/audit-logs",
    analytics: "/admin/analytics",
  },
};
